# Exact stock E310 package contract for the open Wi-Fi baseband shell.
# Pin names and I/O standards are copied from UHD's e31x_pins.xdc.

# AD9361 DATA_CLK is 40 MHz in the required 20 MS/s 2R2T mode. Constrain the
# BUFG output net used by the actual radio logic; nextpnr does not propagate a
# port-level clock declaration through BUFG automatically. FCLK0/GP0 uses the
# separate 100 MHz command-line default. TX data, frame, and forwarded clock
# are all launched by stock-compatible I/O-site ODDRs in this same domain.
create_clock -name radio_clk -period 25.000 [get_nets radio_clk]

set_property LOC AB5 [get_ports {CAT_CTRL_OUT[0]}]
set_property LOC AB6 [get_ports {CAT_CTRL_OUT[1]}]
set_property LOC AB7 [get_ports {CAT_CTRL_OUT[2]}]
set_property LOC AA4 [get_ports {CAT_CTRL_OUT[3]}]
set_property LOC K20 [get_ports {CAT_CTRL_OUT[4]}]
set_property LOC L19 [get_ports {CAT_CTRL_OUT[5]}]
set_property LOC V12 [get_ports {CAT_CTRL_OUT[6]}]
set_property LOC W12 [get_ports {CAT_CTRL_OUT[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_CTRL_OUT[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_CTRL_OUT[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_CTRL_OUT[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_CTRL_OUT[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_CTRL_OUT[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_CTRL_OUT[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_CTRL_OUT[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_CTRL_OUT[7]}]

set_property LOC V4 [get_ports {CAT_CTRL_IN[0]}]
set_property LOC V5 [get_ports {CAT_CTRL_IN[1]}]
set_property LOC U5 [get_ports {CAT_CTRL_IN[2]}]
set_property LOC U6 [get_ports {CAT_CTRL_IN[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_CTRL_IN[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_CTRL_IN[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_CTRL_IN[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_CTRL_IN[3]}]

set_property LOC U11 [get_ports CAT_RESET]
set_property LOC W6 [get_ports CAT_CS]
set_property LOC W5 [get_ports CAT_SCLK]
set_property LOC V7 [get_ports CAT_MOSI]
set_property LOC W7 [get_ports CAT_MISO]
set_property LOC AB1 [get_ports CAT_TXNRX]
set_property LOC AB4 [get_ports CAT_ENABLE]
set_property LOC AB2 [get_ports CAT_ENAGC]
set_property LOC T16 [get_ports CAT_SYNC]
set_property IOSTANDARD LVCMOS18 [get_ports CAT_RESET]
set_property IOSTANDARD LVCMOS18 [get_ports CAT_CS]
set_property IOSTANDARD LVCMOS18 [get_ports CAT_SCLK]
set_property IOSTANDARD LVCMOS18 [get_ports CAT_MOSI]
set_property IOSTANDARD LVCMOS18 [get_ports CAT_MISO]
set_property IOSTANDARD LVCMOS18 [get_ports CAT_TXNRX]
set_property IOSTANDARD LVCMOS18 [get_ports CAT_ENABLE]
set_property IOSTANDARD LVCMOS18 [get_ports CAT_ENAGC]
set_property IOSTANDARD LVCMOS18 [get_ports CAT_SYNC]

set_property LOC L18 [get_ports CAT_DATA_CLK]
set_property LOC N18 [get_ports CAT_RX_FRAME]
set_property LOC R21 [get_ports CAT_FB_CLK]
set_property LOC P22 [get_ports CAT_TX_FRAME]
set_property IOSTANDARD LVCMOS18 [get_ports CAT_DATA_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports CAT_RX_FRAME]
set_property IOSTANDARD LVCMOS18 [get_ports CAT_FB_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports CAT_TX_FRAME]

set_property LOC L16 [get_ports {CAT_P0_D[0]}]
set_property LOC K18 [get_ports {CAT_P0_D[1]}]
set_property LOC L17 [get_ports {CAT_P0_D[2]}]
set_property LOC J17 [get_ports {CAT_P0_D[3]}]
set_property LOC M16 [get_ports {CAT_P0_D[4]}]
set_property LOC J15 [get_ports {CAT_P0_D[5]}]
set_property LOC K16 [get_ports {CAT_P0_D[6]}]
set_property LOC J16 [get_ports {CAT_P0_D[7]}]
set_property LOC N20 [get_ports {CAT_P0_D[8]}]
set_property LOC K15 [get_ports {CAT_P0_D[9]}]
set_property LOC N17 [get_ports {CAT_P0_D[10]}]
set_property LOC M17 [get_ports {CAT_P0_D[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P0_D[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P0_D[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P0_D[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P0_D[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P0_D[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P0_D[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P0_D[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P0_D[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P0_D[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P0_D[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P0_D[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P0_D[11]}]

set_property LOC N19 [get_ports {CAT_P1_D[0]}]
set_property LOC M21 [get_ports {CAT_P1_D[1]}]
set_property LOC P20 [get_ports {CAT_P1_D[2]}]
set_property LOC P15 [get_ports {CAT_P1_D[3]}]
set_property LOC P17 [get_ports {CAT_P1_D[4]}]
set_property LOC P18 [get_ports {CAT_P1_D[5]}]
set_property LOC R20 [get_ports {CAT_P1_D[6]}]
set_property LOC P21 [get_ports {CAT_P1_D[7]}]
set_property LOC M22 [get_ports {CAT_P1_D[8]}]
set_property LOC T17 [get_ports {CAT_P1_D[9]}]
set_property LOC N22 [get_ports {CAT_P1_D[10]}]
set_property LOC N15 [get_ports {CAT_P1_D[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P1_D[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P1_D[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P1_D[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P1_D[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P1_D[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P1_D[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P1_D[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P1_D[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P1_D[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P1_D[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P1_D[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P1_D[11]}]

set_property LOC H19 [get_ports {TX_BANDSEL[2]}]
set_property LOC F21 [get_ports {TX_BANDSEL[1]}]
set_property LOC F22 [get_ports {TX_BANDSEL[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TX_BANDSEL[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TX_BANDSEL[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TX_BANDSEL[2]}]

set_property LOC G20 [get_ports {RX1_BANDSEL[2]}]
set_property LOC G21 [get_ports {RX1_BANDSEL[1]}]
set_property LOC E19 [get_ports {RX1_BANDSEL[0]}]
set_property LOC AA8 [get_ports {RX2_BANDSEL[2]}]
set_property LOC AA9 [get_ports {RX2_BANDSEL[1]}]
set_property LOC AB9 [get_ports {RX2_BANDSEL[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX1_BANDSEL[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX1_BANDSEL[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX1_BANDSEL[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX2_BANDSEL[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX2_BANDSEL[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX2_BANDSEL[2]}]

set_property LOC G19 [get_ports {RX1B_BANDSEL[1]}]
set_property LOC F19 [get_ports {RX1B_BANDSEL[0]}]
set_property LOC B15 [get_ports {RX1C_BANDSEL[1]}]
set_property LOC A19 [get_ports {RX1C_BANDSEL[0]}]
set_property LOC U9 [get_ports {RX2B_BANDSEL[1]}]
set_property LOC Y4 [get_ports {RX2B_BANDSEL[0]}]
set_property LOC U10 [get_ports {RX2C_BANDSEL[1]}]
set_property LOC Y10 [get_ports {RX2C_BANDSEL[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX1B_BANDSEL[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX1B_BANDSEL[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX1C_BANDSEL[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX1C_BANDSEL[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX2B_BANDSEL[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX2B_BANDSEL[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX2C_BANDSEL[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX2C_BANDSEL[1]}]

set_property LOC G22 [get_ports TX_ENABLE1A]
set_property LOC A17 [get_ports TX_ENABLE1B]
set_property LOC H22 [get_ports TX_ENABLE2A]
set_property LOC B16 [get_ports TX_ENABLE2B]
set_property IOSTANDARD LVCMOS33 [get_ports TX_ENABLE1A]
set_property IOSTANDARD LVCMOS33 [get_ports TX_ENABLE1B]
set_property IOSTANDARD LVCMOS33 [get_ports TX_ENABLE2A]
set_property IOSTANDARD LVCMOS33 [get_ports TX_ENABLE2B]

set_property LOC C15 [get_ports VCTXRX1_V1]
set_property LOC B17 [get_ports VCTXRX1_V2]
set_property LOC A16 [get_ports VCTXRX2_V1]
set_property LOC E20 [get_ports VCTXRX2_V2]
set_property LOC E18 [get_ports VCRX1_V1]
set_property LOC F18 [get_ports VCRX1_V2]
set_property LOC F17 [get_ports VCRX2_V1]
set_property LOC G17 [get_ports VCRX2_V2]
set_property IOSTANDARD LVCMOS33 [get_ports VCTXRX1_V1]
set_property IOSTANDARD LVCMOS33 [get_ports VCTXRX1_V2]
set_property IOSTANDARD LVCMOS33 [get_ports VCTXRX2_V1]
set_property IOSTANDARD LVCMOS33 [get_ports VCTXRX2_V2]
set_property IOSTANDARD LVCMOS33 [get_ports VCRX1_V1]
set_property IOSTANDARD LVCMOS33 [get_ports VCRX1_V2]
set_property IOSTANDARD LVCMOS33 [get_ports VCRX2_V1]
set_property IOSTANDARD LVCMOS33 [get_ports VCRX2_V2]

set_property LOC Y11 [get_ports LED_TXRX1_TX]
set_property LOC AB10 [get_ports LED_TXRX1_RX]
set_property LOC AA12 [get_ports LED_RX1_RX]
set_property LOC U12 [get_ports LED_TXRX2_TX]
set_property LOC AB11 [get_ports LED_TXRX2_RX]
set_property LOC AA11 [get_ports LED_RX2_RX]
set_property IOSTANDARD LVCMOS18 [get_ports LED_TXRX1_TX]
set_property IOSTANDARD LVCMOS18 [get_ports LED_TXRX1_RX]
set_property IOSTANDARD LVCMOS18 [get_ports LED_RX1_RX]
set_property IOSTANDARD LVCMOS18 [get_ports LED_TXRX2_TX]
set_property IOSTANDARD LVCMOS18 [get_ports LED_TXRX2_RX]
set_property IOSTANDARD LVCMOS18 [get_ports LED_RX2_RX]
# E310 board power-management SPI, not the AD9361 programming SPI.
set_property PACKAGE_PIN A22 [get_ports AVR_CS_R]
set_property IOSTANDARD LVCMOS33 [get_ports AVR_CS_R]
set_property PACKAGE_PIN B22 [get_ports AVR_IRQ]
set_property IOSTANDARD LVCMOS33 [get_ports AVR_IRQ]
set_property PACKAGE_PIN C22 [get_ports AVR_MISO_R]
set_property IOSTANDARD LVCMOS33 [get_ports AVR_MISO_R]
set_property PACKAGE_PIN A21 [get_ports AVR_MOSI_R]
set_property IOSTANDARD LVCMOS33 [get_ports AVR_MOSI_R]
set_property PACKAGE_PIN D22 [get_ports AVR_SCK_R]
set_property IOSTANDARD LVCMOS33 [get_ports AVR_SCK_R]
